# Script generated by ChatGPT, the prompt was to help me solve a problem from a project with some sample data 
# Does it do well in terms of clean code? Why or why not?

# Load necessary libraries
library(dplyr)
library(stringr)
library(tidyr)

# Example data frame with an additional 'name' column
df <- data.frame(
  name = c("Item1", "Item2", "Item3", "Item4"),
  column_name = c(
    "apple orange banana", 
    "banana orange grape", 
    "grape fruit apple banana", 
    "orange apple grape"
  ),
  stringsAsFactors = FALSE
)

# Example list of two-word combinations
combinations_list <- list(
  c("apple", "banana"),
  c("orange", "grape"),
  c("banana", "grape")
)

# Function to check if combination is in a sentence
check_combinations <- function(sentence, combinations) {
  words <- unlist(strsplit(sentence, " "))
  found_combinations <- sapply(combinations, function(combo) {
    if (all(combo %in% words)) {
      return(combo)
    } else {
      return(NULL)
    }
  })
  # Filter out NULLs and only keep non-NULL results
  found_combinations <- found_combinations[lengths(found_combinations) > 0]
  # Concatenate matched words for each combination found 
  matched_words <- sapply(found_combinations, function(x) paste(x, collapse = ", "))
  return(matched_words)
}

# Apply function to each row in the data frame with an additional column for name
result <- df %>%
  rowwise() %>%
  mutate(
    matched_combinations = list(check_combinations(column_name, combinations_list))
  ) %>% 
  ungroup() %>%
  filter(lengths(matched_combinations) > 0) %>%
  select(name, column_name, matched_combinations) %>%
  unnest(matched_combinations)

# Display the result
print(result)
